services:
  authdb:
    image: 'postgres:latest'
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: IgnacioVillarreal
      POSTGRES_PASSWORD: 12345678
      POSTGRES_DB: authdb
    volumes:
      - authdb:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "admin" ]
      interval: 10s
      timeout: 5s
      retries: 5

  authapi:
    build:
      dockerfile: Dockerfile
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    ports:
      - 8080:8080
    depends_on:
      authdb:
        condition: service_healthy
    restart: on-failure

volumes:
  authdb: