services:
  auth_api:
    build:
      dockerfile: Dockerfile
    container_name: auth_api
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    ports:
      - "8080:8080"
    restart: on-failure

networks:
  default:
    external:
      name: api_net