services:
  auth_api:
    build:
      dockerfile: Dockerfile
    container_name: auth_api
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    ports:
      - "8080:8080"
    depends_on:
      postgresql_auth_api:
        condition: service_healthy
      rabbitmq_auth_api:
        condition: service_healthy
    restart: on-failure

  postgresql_auth_api:
    image: postgres:latest
    container_name: postgresql_auth_api
    environment:
      - POSTGRES_USER=IgnacioVillarreal
      - POSTGRES_PASSWORD=12345678
      - POSTGRES_DB=authdb
    ports:
      - "5432:5432"
    volumes:
      - authdb_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "IgnacioVillarreal", "-d", "mediadb"]
      interval: 10s
      timeout: 5s
      retries: 5

  rabbitmq_auth_api:
    image: rabbitmq:management
    container_name: rabbitmq_auth_api
    environment:
      - RABBITMQ_DEFAULT_USER=IgnacioVillarreal
      - RABBITMQ_DEFAULT_PASS=12345678
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: [ "CMD", "rabbitmq-diagnostics", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  authdb_data: