spring:
  datasource:
    url: jdbc:postgresql://postgresql:5432/main_db
    username: ignacio
    password: 12345678
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        default_schema: auth_schema
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  rabbitmq:
    host: rabbitmq
    port: 5672
    username: ignacio
    password: 12345678

  flyway:
    enabled: true
    schemas: auth_schema
    locations: classpath:db/migration

jwt:
  secret: 23e586808ea364607079ec5b830ba702e80680339864b175eb2f5a13abd214e7
  expiration:
    access-token-ms: 1440000
    refresh-token-ms: 10080000

cors:
  allowed-origins:
    - http://rescuemeapp:4200/

logging:
  level:
    org:
      springframework:
        security: DEBUG