spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/main_db
    username: ignacio
    password: 12345678
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        default_schema: auth_schema
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  rabbitmq:
    host: rabbitmq
    port: 5672
    username: ignacio
    password: 12345678
    template:
      mandatory: true

  flyway:
    enabled: true
    schemas: auth_schema
    locations: classpath:db/migration

  cache:
    type: redis
  data:
    redis:
      host: redis
      port: 6379

jwt:
  secret: 23e586808ea364607079ec5b830ba702e80680339864b175eb2f5a13abd214e7
  expiration:
    access-token-ms: 1440000
    refresh-token-ms: 10080000

cors:
  allowed-origins:
    - http://rescuemeapp:4200/
    - http://rescue_me_app:4200/

rabbit:
  exchange:
    auth: authApi.exchange
  queue:
    initiate-user-registration-command: authApi.initiateUserRegistrationCommand.queue
    rollback-user-registration-command: authApi.rollbackUserRegistrationCommand.queue
    confirm-user-registration-command: authApi.confirmUserRegistrationCommand.queue
    failure-user-registration-reply: authApi.failureUserRegistrationReply.queue
    success-user-registration-reply: authApi.successUserRegistrationReply.queue
  routing-key:
    initiate-user-registration-command: authApi.initiateUserRegistrationCommand.routingKey
    rollback-user-registration-command: authApi.rollbackUserRegistrationCommand.routingKey
    confirm-user-registration-command: authApi.confirmUserRegistrationCommand.routingKey
    failure-user-registration-reply: authApi.failureUserRegistrationReply.routingKey
    success-user-registration-reply: authApi.successUserRegistrationReply.routingKey

logging:
  level:
    com.api: DEBUG
    org.springframework.security: DEBUG