spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: admin
    password: password
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  test:
    database:
      replace: any
jwt:
  secret: 23e586808ea364607079ec5b830ba702e80680339864b175eb2f5a13abd214e7
  expiration_token: 1440000
  expiration_refresh_token: 10080000
cors:
  allowed-origin: http://localhost:4200/
logging:
  level:
    org:
      springframework:
        security: DEBUG